name: Tests

on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: php-actions/composer@v6
            - name: PHPUnit Tests
              uses: php-actions/phpunit@v3
              with:
                  version: 11.5
                  php_version: 8.3
                  test_suffix: Test.php
                  configuration: phpunit.xml
